# Generated by Django 2.1.10 on 2019-07-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zohoid', models.CharField(max_length=50)),
                ('bname', models.TextField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('leadstatus', models.CharField(max_length=35)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('zip', models.IntegerField()),
                ('state', models.CharField(max_length=25)),
                ('coord', models.TextField()),
                ('abn', models.CharField(max_length=20)),
                ('account_name', models.TextField()),
                ('bsb', models.CharField(max_length=15)),
                ('account_number', models.CharField(max_length=15)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='business_attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.business')),
            ],
        ),
        migrations.CreateModel(
            name='connectstar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starid', models.CharField(max_length=25)),
                ('vin', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='makes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='original_vins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('stock_number', models.TextField()),
                ('location', models.TextField()),
                ('date', models.DateField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.business')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='unidentified_vins_17character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.business')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.original_vins')),
            ],
        ),
        migrations.CreateModel(
            name='vin_attachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='vin_conflicts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('originalvins_business', models.TextField()),
                ('conflict_location', models.TextField()),
                ('conflict_stocknumber', models.TextField()),
                ('conflict_filename', models.TextField()),
                ('cnflict_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.business')),
            ],
        ),
        migrations.CreateModel(
            name='vinfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=100)),
                ('notes', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.business')),
            ],
        ),
        migrations.CreateModel(
            name='washed_vins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleairbagid', models.CharField(max_length=50)),
                ('vehicleid', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=50)),
                ('pranum', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('airbaglocation', models.CharField(max_length=50)),
                ('isalpha', models.CharField(max_length=50)),
                ('issubmitted', models.CharField(max_length=50)),
                ('location', models.TextField()),
                ('stock_number', models.TextField()),
                ('barcode', models.TextField()),
                ('star_vendor_no', models.TextField()),
                ('location_status', models.TextField()),
                ('no_collected', models.TextField()),
                ('in_possession', models.TextField()),
                ('warehouse', models.TextField()),
                ('recycler_inv', models.TextField()),
                ('bagcollectiondate', models.DateField()),
                ('bagcollectedby', models.TextField()),
                ('starid', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.business')),
            ],
        ),
        migrations.CreateModel(
            name='weeks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wstart', models.CharField(max_length=4)),
                ('wend', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=15)),
                ('year', models.IntegerField()),
                ('weekno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wiki_vincodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('make', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='vin_attachments',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinwash.washed_vins'),
        ),
        migrations.AddField(
            model_name='original_vins',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vinwash.vinfile'),
        ),
    ]
