# Generated by Django 2.1.10 on 2019-07-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washed_vins',
            name='vehicleairbagid',
        ),
        migrations.AlterField(
            model_name='business',
            name='abn',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='account_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='account_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='bname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='bsb',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='coord',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='fax',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='leadstatus',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='mobile',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='street',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='zip',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='business_attachments',
            name='attachment_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='connectstar',
            name='starid',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='connectstar',
            name='vin',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='makes',
            name='manufacturer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='original_vins',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='original_vins',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='original_vins',
            name='stock_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='original_vins',
            name='vin',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vin_attachments',
            name='attachment_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vin_conflicts',
            name='conflict_filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vin_conflicts',
            name='conflict_location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vin_conflicts',
            name='conflict_stocknumber',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vin_conflicts',
            name='originalvins_business',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vin_conflicts',
            name='vin',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='vinfile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vinfile',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vinfile',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='airbaglocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='bagcollectedby',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='bagcollectiondate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='barcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='in_possession',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='isalpha',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='issubmitted',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='location_status',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='no_collected',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='pranum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='recycler_inv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='series',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='star_vendor_no',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='starid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='stock_number',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='vehicleid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='vin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='warehouse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='washed_vins',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='month',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='weekno',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='wend',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='wstart',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='weeks',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wiki_vincodes',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wiki_vincodes',
            name='make',
            field=models.TextField(null=True),
        ),
    ]
