# Generated by Django 2.1.10 on 2019-07-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0003_auto_20190725_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washed_vins',
            name='business',
        ),
        migrations.AddField(
            model_name='washed_vins',
            name='fileid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vinwash.vinfile'),
        ),
    ]
