# Generated by Django 2.1.10 on 2019-07-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0004_auto_20190726_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='washed_vins',
            old_name='fileid',
            new_name='file',
        ),
    ]
