# Generated by Django 2.1.10 on 2019-07-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0005_auto_20190726_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_vins',
            name='wiki_oem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_vins',
            name='wiki_prefix',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
