# Generated by Django 2.1.10 on 2019-07-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0006_auto_20190726_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_vins',
            name='wiki_oem',
        ),
        migrations.RemoveField(
            model_name='original_vins',
            name='wiki_prefix',
        ),
        migrations.AddField(
            model_name='original_vins',
            name='wiki_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
