# Generated by Django 2.1.10 on 2019-08-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0007_auto_20190726_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_vins',
            name='img',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vinfile',
            name='filetype',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
