# Generated by Django 2.1.10 on 2019-08-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0008_auto_20190801_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='original_extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('model', models.TextField(null=True)),
                ('year', models.TextField(null=True)),
                ('inventoried', models.TextField(null=True)),
                ('odoreading', models.TextField(null=True)),
                ('engine', models.TextField(null=True)),
                ('gearboxtype', models.TextField(null=True)),
                ('gears', models.TextField(null=True)),
                ('doors', models.TextField(null=True)),
                ('sute', models.TextField(null=True)),
                ('registration', models.TextField(null=True)),
                ('cod', models.TextField(null=True)),
                ('enginenumber', models.TextField(null=True)),
                ('purchasedate', models.TextField(null=True)),
                ('fueltype', models.TextField(null=True)),
                ('bodystyle', models.TextField(null=True)),
            ],
        ),
    ]
