# Generated by Django 2.1.10 on 2019-08-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0009_original_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_extension',
            name='extension',
            field=models.TextField(null=True),
        ),
    ]
