# Generated by Django 2.1.10 on 2019-08-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0010_original_extension_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_extension',
            name='bodystyle',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='cod',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='doors',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='enginenumber',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='fueltype',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='gearboxtype',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='gears',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='image',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='inventoried',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='model',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='odoreading',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='purchasedate',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='registration',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='sute',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='year',
        ),
    ]
