# Generated by Django 2.1.10 on 2019-08-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0011_auto_20190805_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_extension',
            name='bodystyle',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='cod',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='doors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='engine',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='enginenumber',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='extension',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='fueltype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='gearboxtype',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='gears',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='inventoried',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='model',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='odoreading',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='purchasedate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='registration',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='sute',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='original_extension',
            name='year',
            field=models.TextField(null=True),
        ),
    ]
