# Generated by Django 2.1.10 on 2019-08-05 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0012_auto_20190805_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='original_extension',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='original_extension',
            name='image',
        ),
    ]
