# Generated by Django 2.1.10 on 2019-08-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinwash', '0013_auto_20190805_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='original_extension',
            name='classification',
            field=models.TextField(null=True),
        ),
    ]
